### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by bfontaine** [Unrepl/unravel#10]
Hello,
Could you please use `git tag` so we can e.g. checkout the `0.1.6` code by running `git checkout 0.1.6`?

Thanks!

**Comment by pesterhazy** [comment]
Great idea. Does this work for you @bfontaine? https://github.com/pesterhazy/unravel/tree/0.2.2

By the way, I saw that you started a homebrew formula for `unravel`. That sounds like a great idea to me. Did you encounter any issues?

**Comment by bfontaine** [comment]
Perfect, thanks!

> By the way, I saw that you started a homebrew formula for `unravel`. That sounds like a great idea to me. Did you encounter any issues?

I had an issue with `lumo`; I patched your `package.json` to use `lumo` 1.6.0 instead of 1.2.0. I see you bumped it for the release so I removed the patch.

I also had an issue with the `blob.clj` resource path; but here again you fixed it for the release.

**Comment by pesterhazy** [comment]
@bfontaine nice, ```brew install --HEAD bfontaine/utils/unravel```works for me!

Mind if I add this to the README?

**Comment by bfontaine** [comment]
Of course not, but use `brew install bfontaine/utils/unravel` instead, it installs the 0.2.2 release 😃
