### ISSUE TITLE
Try a compliment

### ISSUE THREAD

**Issue by pesterhazy** [Unrepl/unravel#11]
Experiment with sending a concatenated https://github.com/alexander-yakushev/compliment blob to the repl and using that for completion.

**Comment by arichiardi** [comment]
Specifically we'd need something to make a blob out of any library (and dependencies?), using @cgrand's already ready code [here](https://github.com/cgrand/unrepl/blob/master/tasks/leiningen/unrepl_make_blob.clj).

I have already worked on something similar for boot (it was used to pack things for bootstrapped repls): https://github.com/Lambda-X/boot-pack-source/blob/master/src/replumb/boot_pack_source.clj#L104 

Also maybe [mranderson](https://github.com/typedclojure/mranderson) has some utility for doing this.

Additionally:

> pesterhazy [4:01 AM] 
> we also need gensym'ed namespaces for isoluation

**Comment by pesterhazy** [comment]
https://github.com/pesterhazy/unravel/pull/12

**Comment by pesterhazy** [comment]
See https://github.com/Unrepl/unravel/pull/36
