### ISSUE TITLE
Copy and pasting is weird

### ISSUE THREAD

**Issue by pesterhazy** [Unrepl/unravel#15]
Every character pasted is interpreted as a keystroke

Unravel should debounce/throttle user input

**Comment by arichiardi** [comment]
I hope this is not going to get as crazy as the `node` repl. There is a weird [`.editor`](https://stackoverflow.com/questions/29203892/how-to-write-multiple-lines-of-code-in-node-repl) mode that I really cannot understand. Hopefully not a `stream` limitation.

**Comment by pesterhazy** [comment]
Interesting. Can you explain how the node repl handle pasting?

**Comment by arichiardi** [comment]
Fortunately/unfortunately I haven't had the joy of looking at the how, just wanted to point out a pain point. Will explore more.

**Comment by pesterhazy** [comment]
This is how lumo does it: https://github.com/cgrand/lumo/blob/master/src/js/repl.js#L77-L82
