### ISSUE TITLE
REPL hangs when java.time.Instant/parse is called from prompt

### ISSUE THREAD

**Issue by ghost** [Unrepl/unravel#45]
when  `java.time.Instant/parse` is called at the repl prompt, the session hangs and not even `ctrl-c` can stop execution.  Had to use `ctrl-d` to exit.  When `java.time.Instant/parse` is called within the body of some other expression, it works fine.

**Comment by cgrand** [comment]
Reproduced. An even simpler case is `(Object.)` the unrepl message is

```clj
[:eval #unrepl/object [#unrepl.java/class java.lang.Object "0x52cb4cdc" "java.lang.Object@52cb4cdc" {:bean {, #unrepl/... nil #unrepl/... {:get (unrepl.replG__49317/fetch :G__53895)}}}] 2]
```

but it is never seen by unravel (according to `--debug`)

**Comment by cgrand** [comment]
I updated to latest unrepl (the one with the print overhaul) and it fixed the problem. I don't like to close an issue without understanding it.

**Comment by cgrand** [comment]
Ah! the blob in master is based on a bad unrepl (a revision with quoting stuff)

**Comment by pesterhazy** [comment]
@jerrycastro thanks for the report. Couldn't repro so I'm assuming this is fixed in master - please reopen if not!
