### ISSUE TITLE
Jack in with auto-discovery

### ISSUE THREAD

**Issue by pesterhazy** [Unrepl/unravel#49]
Add cli flag `--jack-in`, which automatically starts a new Clojure process for you (rather than attaching to an existing process)

There should also be an option to specify the way to start the server:

- plain clojure (java -cp ...)
- https://github.com/clojure/tools.deps.alpha
- boot
- lein

To negotiate a random port:

```
$ boot -i "(do (require 'clojure.core.server) (let [srv (clojure.core.server/start-server {:name :repl :port 0 :accept 'clojure.core.server/repl})] (prn [:jack-in/ready {:port (.getLocalPort srv)}])))" wait
[:jack-in/ready {:port 61946}]
```

**Comment by cgrand** [comment]
Ah it has been on my mind recently. Rather than a flag I would make it the default (when no [host] port). Following a logic like:

```
Is there a deps.edn ?
Is there a project.clj ?
etc.
```

**Comment by volrath** [comment]
For Leiningen projects, random port negotiation might have to be handled differently, maybe even from within unravel.

AFAIK, there's no similar lein CLI API for boot's `-i`, closest I could find was a plugin called [`lein-exec`](https://github.com/kumarshantanu/lein-exec). 

If you run

```
JVM_OPTS='-Dclojure.server.repl={:port,0,:accept,clojure.core.server/repl}' lein repl
```

You get a random port indeed, but not an easy indication on which port is it.

--

besides this, love the idea :)

**Comment by cgrand** [comment]
@volrath for lein
```sh
lein trampoline run -m clojure.main -e "(do (require 'clojure.core.server) (let [srv (clojure.core.server/start-server {:name :repl :port 0 :accept 'clojure.core.server/repl :server-daemon false})] (prn [:jack-in/ready {:port (.getLocalPort srv)}])))"
```

**Comment by cgrand** [comment]
or even better
```sh
java -cp `lein classpath` clojure.main -e "(do (require 'clojure.core.server) (let [srv (clojure.core.server/start-server {:name :repl :port 0 :accept 'clojure.core.server/repl :server-daemon false})] (prn [:jack-in/ready {:port (.getLocalPort srv)}])))"
```

**Comment by volrath** [comment]
@cgrand fantastic! I'm implementing this on unrepl.el *today* :)

**Comment by cgrand** [comment]
@volrath bonus points for finding a reliable way to cache `lein deps` in a way that doesn't break when switching branches

**Comment by pesterhazy** [comment]
Fixed in master
