### ISSUE TITLE
Ellipsis numbers seem off

### ISSUE THREAD

**Issue by arichiardi** [Unrepl/unravel#5]
Hi @pesterhazy!

First time that today I have tried unravel and I so so like it!
As a newbie to the ellipsis feature, I tried the following and I paste it as it is. Some numbers after the `#__` seem off a bit, display only, because when I evaluate everything is fine (see `#__5`, `#__6`, `#__7`).

```
unrepl.replG__382=> (def t (range 0 100))
#unrepl/object [#unrepl.java/class clojure.lang.Var "0x18831dd7" {:unrepl.ref/status :ready, :unrepl.ref/val (0 1 2 3 4 5 6 7 8 9 #__3)} {:bean {#__4 #__5}}]
unrepl.replG__382=> #__4
unrepl.replG__382=> {:watches {}, :validator nil, :public true, :threadBinding nil, :bound true, :dynamic false, :macro false, :class #unrepl.java/class clojure.lang.Var, :rawRoot (0 1 2 3 4 5 6 7 8 9 #__6), :tag nil}
unrepl.replG__382=> #__6
(10 11 12 13 14 15 16 17 18 19 #__7)
unrepl.replG__382=> #__4
{:watches {}, :validator nil, :public true, :threadBinding nil, :bound true, :dynamic false, :macro false, :class #unrepl.java/class clojure.lang.Var, :rawRoot (0 1 2 3 4 5 6 7 8 9 #__8), :tag nil}
unrepl.replG__382=> #__5
unrepl.replG__382=> #__6
unrepl.replG__382=> (10 11 12 13 14 15 16 17 18 19 #__9)
unrepl.replG__382=> #__7
(20 21 22 23 24 25 26 27 28 29 #__10)
unrepl.replG__382=> #__9
(20 21 22 23 24 25 26 27 28 29 #__11)
```

Super positive feedback about the visual clues! Great job so far and super quick startup.

**Comment by cgrand** [comment]
I see what's happening there: ellipsis in a map are made of: a true ellipsis and a padding ellipsis (at the protocol level to have a map representation with an even number of items). The padding ellipsis should be rendered differently (or not at all).

**Comment by pesterhazy** [comment]
Thanks for the report! I can reproduce this locally and will fix before the next release.

The var shouldn't be printed as `#unrepl/object` but as `#'user/t`. @cgrand, should unrepl provide a special print method for vars? Or should this be handled by the client?

Second, the object is printed with the `bean` key, which I think is not interesting for unravel users for now. So it should be safe to leave out the `bean` key.

**Comment by pesterhazy** [comment]
See https://github.com/pesterhazy/unravel/issues/6 for vars

**Comment by arichiardi** [comment]
Thanks for looking into it :+1: I have forgot to say this is `unrepl` and `unravel` both master (as of the date of the issue :smile:)

**Comment by pesterhazy** [comment]
@arichiardi does this work for you now, at least for the `def` use case?

**Comment by arichiardi** [comment]
Will try it out.

**Comment by arichiardi** [comment]
Still something is missing here, look at the end...I am sneaking in a feature request ;)

```
Unravel 0.2.1 connected to localhost:5555

Type ^O for full docs of symbol under cursor, ^D to quit
Enter #__help for help

unrepl.replG__382=> (range 0 10)
(0 1 2 3 4 5 6 7 8 9)
unrepl.replG__382=> (range 0 100)
(0 1 2 3 4 5 6 7 8 9 #__1)
unrepl.replG__382=> #__1
(10 11 12 13 14 15 16 17 18 19 #__2)
unrepl.replG__382=> #__2
(20 21 22 23 24 25 26 27 28 29 #__3)
unrepl.replG__382=> #__1
(10 11 12 13 14 15 16 17 18 19 #__4)
unrepl.replG__382=> #__5
unrepl.replG__382=> #__6
unrepl.replG__382=>
```

The feauture would be the possibility to skip ahead: say I know I am going to need things after `#__4` and they are not in `#__6`. I will write `#__7` at the REPL. It is a UX bonus I guess. Don't know if possible.

Thanks for the quick fix!

**Comment by cgrand** [comment]
My answer would be to use `drop`.

**Comment by arichiardi** [comment]
Yes, but `unravel` spoiled me :smile:

**Comment by cgrand** [comment]
however from a ux perspective having something like `#*` to refer to *the last printed ellipisis* would be interesting I think.

**Comment by arichiardi** [comment]
This for me is really a killer feature that every REPL should have, probably even worth a separate lib for standardizing on printing. Nrepl provides [something similar](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/print_method.clj), but yours is way more advanced.
