### ISSUE TITLE
Spurious prompt when pasting

### ISSUE THREAD

**Issue by pesterhazy** [Unrepl/unravel#55]
If I paste `()` into the prompt and press enter:

```
user=> ()
user=> ()
user=>
```

The second `user=>` prompt shouldn't be there.

However if I type the same string, `()`, manually, it works:

```
user=> ()
()
user=>
```

**Comment by cgrand** [comment]
With parfix I guess

**Comment by pesterhazy** [comment]
@cgrand actually no - it works correctly with parfix enabled, incorrectly with parfix disabled

**Comment by cgrand** [comment]
hah! with colors it makes sense
