### ISSUE TITLE
Compliment used without requiring it

### ISSUE THREAD

**Issue by SevereOverfl0w** [Unrepl/unravel#63]
When using `--flag compliment` and hitting `<tab>`, unravel locks up. This is because of an exception caused by using compliment.core without first requiring the namespace.

**Comment by SevereOverfl0w** [comment]
Workaround is to `(require 'compliment.core)` as you initialize the build environment.

**Comment by pesterhazy** [comment]
Tried to require `compilment.core` in the tooling connection: https://github.com/Unrepl/unravel/pull/68/commits/d14dceb36852104b837d5bba286822e847d90908

But this doesn't work — I'm guessing this is because the tooling connection is also used for the side-loader and blocks while the `require` is active.

**Comment by pesterhazy** [comment]
CC: @cgrand — is requiring a sideloaded ns on a (single) aux connection intended to work?

**Comment by cgrand** [comment]
Yes it is intended to work, the actual side loading occurs on a 3rd conn.

**Comment by pesterhazy** [comment]
```(do (require 'compliment.core) (compliment.core/candidates)))```

didn't work but

```(do (require 'compliment.core) ((resolve 'compliment.core/candidates) "asdf")))```

does

**Comment by cgrand** [comment]
Was your `do` top-level?

**Comment by pesterhazy** [comment]
Top level of the form sent to aux, yes — why?

**Comment by cgrand** [comment]
because `(do (require 'compliment.core) (compliment.core/candidates)))` works only at top level.
top-level `do`s are spliced and their forms are evaluated one by one. So any ns/var change can be seen by next forms. If you replace `do` by `let []` it won't work.

**Comment by cgrand** [comment]
```clj
(do (create-ns 'fooz) (intern 'fooz 'bar 42) fooz/bar)
[:read {:from [1 1], :to [2 1], :offset 0, :len 55} 1]
[:started-eval {:actions {:interrupt (unrepl.replG__1244/interrupt! :session1865 1), :background (unrepl.replG__1244/background! :session1865 1)}} 1]
[:eval 42 1]```

**Comment by pesterhazy** [comment]
Aha! I was wrong actually just now — what I'm sending is actually

```
[:unravel/rpc eval-id (do (require 'a.b) ...]
```

Combined with what you said, that explains the problem.
