### ISSUE TITLE
unravel brew formulae is broken

### ISSUE THREAD

**Issue by developer2019** [Unrepl/unravel#65]
Please fix macOS brew formulae to install lumo pre-1.7.0. Now it installs lumo 1.7.0 and unravel doesn't work after installation:
```
$ unravel localhost 50505
evalmachine.<anonymous>:22var reader = cljs.reader.push_back_reader.call(null,s); ^TypeError: Cannot read property 'call' of undefined at unravel$lisp$safe_read_string (evalmachine.<anonymous>:22:42) at Transform._transform (evalmachine.<anonymous>:56:60) at Transform._read (_stream_transform.js:186:10) at Transform._write (_stream_transform.js:174:12) at doWrite (_stream_writable.js:385:12) at writeOrBuffer (_stream_writable.js:371:5) at Transform.Writable.write (_stream_writable.js:288:11) at Transform.ondata (_stream_readable.js:642:20) at emitOne (events.js:115:13) at Transform.emit (events.js:210:7)
```

**Comment by pesterhazy** [comment]
I've created a new unravel formula. Now the installation should be independent of the installed lumo/npm/yarn.

Installation instructions are here: https://github.com/Unrepl/unravel#simple-installation

@developer2019 could you give `brew install unrepl/bin/unravel` a spin?

**Comment by pesterhazy** [comment]
Closing - please reopen if you encounter any problems

**Comment by kommen** [comment]
I had this problem. Installing unravel with `brew install unrepl/bin/unravel` fixed it for me. Thanks @pesterhazy!
