### ISSUE TITLE
Homebrew unravel package was deleted

### ISSUE THREAD

**Issue by KingMob** [Unrepl/unravel#73]
Someone [deleted the unravel homebrew package](https://github.com/Homebrew/homebrew-core/commit/bdd059c9af521c3ad31294e279444768a68a1573).

Dunno if this is a concern or not, but the installation instructions still refer to homebrew, fyi.

**Comment by bbatsov** [comment]
Seems this originated from Lumo failing to build from source. Given its current status (not maintained), I guess that's not really a surprise.
